// Generated by @taserjs/cli. Do not edit directly.
import { createTaserApp } from "@taserjs/runtime";
import taser from "../taser.js";
import route_0 from "../routes/health.get.js";
import route_1 from "../routes/index.get.js";

export type LayoutTree = {

};

export const layoutManifest = {

} as const;

export const routeManifest = {
  layouts: layoutManifest,
  routes: {
    "/health": {
      GET: {
        layouts: [],
        route: route_0,
      },
    },
    "/": {
      GET: {
        layouts: [],
        route: route_1,
      },
    },
  },
} as const;

export type RouteManifest = typeof routeManifest;
export type AppManifest = RouteManifest;

export const app = createTaserApp(routeManifest, taser);
export default app;
export const createApp = (overrideTaser?: typeof taser) =>
  createTaserApp(routeManifest, overrideTaser ?? taser);

export type RoutePath = "/health" | "/";

export type LayoutHierarchy = {

};

export type RouteByPathMethod = {
    "/health": {
      GET: {
        layouts: readonly [];
      };
    };
    "/": {
      GET: {
        layouts: readonly [];
      };
    };
};

export type AppContext = typeof taser.$Infer.Context;

declare module "@taserjs/router" {
  interface RouterRegister {
    RoutePath: RoutePath;
    LayoutTree: LayoutTree;
    LayoutHierarchy: LayoutHierarchy;
    RouteByPathMethod: RouteByPathMethod;
    AppContext: AppContext;
  }
}
