import type { ResolvedGeneratorConfig } from '../../src/config/schema.js'
import type { GeneratorRunOptions } from '../../src/config/schema.js'
import { resolveGeneratorConfig } from '../../src/config/resolve.js'
import { toScanOptions } from '../../src/config/emit-options.js'
import { walkRouteFiles } from '../../src/fs/walk.js'
import { buildGeneratedModelFromScan } from '../../src/model/build-model.js'
import { scanRouteFiles } from '../../src/scan/scan-routes.js'
import { routesImportPrefix } from '../../src/support/paths.js'

export const testGeneratorConfig = {
  ignorePrefix: '-',
  ignorePattern: undefined,
  extension: true as const,
  validate: false,
} satisfies Pick<
  ResolvedGeneratorConfig,
  'ignorePrefix' | 'ignorePattern' | 'extension' | 'validate'
>

export const testEmitOptions = {
  extension: true as const,
  quotes: 'single' as const,
  semi: false,
  header: [
    '/* eslint-disable */',
    '// Auto-generated by @taserjs/router-generator — do not edit.',
    '',
  ],
  footer: [] as string[],
  format: false,
}

export function resolveTestConfig(
  options: GeneratorRunOptions = {},
): ResolvedGeneratorConfig {
  return resolveGeneratorConfig({
    validate: false,
    format: false,
    ...options,
  })
}

export async function buildTestModel(
  routesDir: string,
  outputFile: string,
  options: GeneratorRunOptions = {},
) {
  const config = resolveTestConfig({ routes: routesDir, output: outputFile, ...options })
  const routesImportBase = routesImportPrefix(routesDir, outputFile)
  const absoluteFiles = await walkRouteFiles(routesDir, config)
  const scan = await scanRouteFiles(routesDir, routesImportBase, absoluteFiles, toScanOptions(config))
  return buildGeneratedModelFromScan(scan)
}
