import { scanAndBuildModel, type ScanAndBuildOptions } from "../../src/generator/scan-and-build.js";
import { DEFAULT_IGNORE } from "../../src/constants.js";

export const testGeneratorConfig = {
  ignore: [...DEFAULT_IGNORE],
  extension: true as const,
  validate: false,
};

export const testEmitOptions = {
  extension: true as const,
  quotes: "single" as const,
  semi: false,
  header: [
    "/* eslint-disable */",
    "// Auto-generated by @taserjs/router-generator — do not edit.",
    "",
  ],
  footer: [] as string[],
  format: false,
};

export async function buildTestModel(
  routesDir: string,
  _unused?: string,
  options: Partial<ScanAndBuildOptions> = {},
) {
  return scanAndBuildModel({
    routesDir,
    routesImportBase: options.routesImportBase ?? "./routes",
    extension: true,
    validate: false,
    ...options,
  });
}
