import { scanAndBuildModel, type ScanAndBuildOptions } from "../../src/index.js";
import { DEFAULT_IGNORE } from "../../src/constants.js";

export const testGeneratorConfig = {
  ignore: [...DEFAULT_IGNORE],
  extension: true as const,
};

export const testEmitOptions = {
  extension: true as const,
  header: [
    "/* eslint-disable */",
    "// Auto-generated by @taserjs/router-generator — do not edit.",
    "",
  ],
};

export async function buildTestModel(
  routesDir: string,
  _unused?: string,
  options: Partial<ScanAndBuildOptions> = {},
) {
  return scanAndBuildModel({
    routesDir,
    routesImportBase: options.routesImportBase ?? "./routes",
    extension: true,
    ...options,
  });
}
