/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as MotivationRouteImport } from './routes/motivation'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as OgDocsSplatRouteImport } from './routes/og/docs/$'
import { Route as OgHomeImageDotwebpRouteImport } from './routes/og/home/image[.]webp'
import { Route as OgMotivationImageDotwebpRouteImport } from './routes/og/motivation/image[.]webp'
import { Route as OgSponsorImageDotwebpRouteImport } from './routes/og/sponsor/image[.]webp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MotivationRoute = MotivationRouteImport.update({
  id: '/motivation',
  path: '/motivation',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const OgDocsSplatRoute = OgDocsSplatRouteImport.update({
  id: '/og/docs/$',
  path: '/og/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgHomeImageDotwebpRoute = OgHomeImageDotwebpRouteImport.update({
  id: '/og/home/image.webp',
  path: '/og/home/image.webp',
  getParentRoute: () => rootRouteImport,
} as any)
const OgMotivationImageDotwebpRoute =
  OgMotivationImageDotwebpRouteImport.update({
    id: '/og/motivation/image.webp',
    path: '/og/motivation/image.webp',
    getParentRoute: () => rootRouteImport,
  } as any)
const OgSponsorImageDotwebpRoute = OgSponsorImageDotwebpRouteImport.update({
  id: '/og/sponsor/image.webp',
  path: '/og/sponsor/image.webp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/motivation': typeof MotivationRoute
  '/sponsor': typeof SponsorRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/og/home/image.webp': typeof OgHomeImageDotwebpRoute
  '/og/motivation/image.webp': typeof OgMotivationImageDotwebpRoute
  '/og/sponsor/image.webp': typeof OgSponsorImageDotwebpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/motivation': typeof MotivationRoute
  '/sponsor': typeof SponsorRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/og/home/image.webp': typeof OgHomeImageDotwebpRoute
  '/og/motivation/image.webp': typeof OgMotivationImageDotwebpRoute
  '/og/sponsor/image.webp': typeof OgSponsorImageDotwebpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/motivation': typeof MotivationRoute
  '/sponsor': typeof SponsorRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/og/docs/$': typeof OgDocsSplatRoute
  '/og/home/image.webp': typeof OgHomeImageDotwebpRoute
  '/og/motivation/image.webp': typeof OgMotivationImageDotwebpRoute
  '/og/sponsor/image.webp': typeof OgSponsorImageDotwebpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/motivation'
    | '/sponsor'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/og/docs/$'
    | '/og/home/image.webp'
    | '/og/motivation/image.webp'
    | '/og/sponsor/image.webp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/motivation'
    | '/sponsor'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/og/docs/$'
    | '/og/home/image.webp'
    | '/og/motivation/image.webp'
    | '/og/sponsor/image.webp'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/motivation'
    | '/sponsor'
    | '/api/search'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/og/docs/$'
    | '/og/home/image.webp'
    | '/og/motivation/image.webp'
    | '/og/sponsor/image.webp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MotivationRoute: typeof MotivationRoute
  SponsorRoute: typeof SponsorRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  OgDocsSplatRoute: typeof OgDocsSplatRoute
  OgHomeImageDotwebpRoute: typeof OgHomeImageDotwebpRoute
  OgMotivationImageDotwebpRoute: typeof OgMotivationImageDotwebpRoute
  OgSponsorImageDotwebpRoute: typeof OgSponsorImageDotwebpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motivation': {
      id: '/motivation'
      path: '/motivation'
      fullPath: '/motivation'
      preLoaderRoute: typeof MotivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/docs/$': {
      id: '/og/docs/$'
      path: '/og/docs/$'
      fullPath: '/og/docs/$'
      preLoaderRoute: typeof OgDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/home/image.webp': {
      id: '/og/home/image.webp'
      path: '/og/home/image.webp'
      fullPath: '/og/home/image.webp'
      preLoaderRoute: typeof OgHomeImageDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/motivation/image.webp': {
      id: '/og/motivation/image.webp'
      path: '/og/motivation/image.webp'
      fullPath: '/og/motivation/image.webp'
      preLoaderRoute: typeof OgMotivationImageDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/sponsor/image.webp': {
      id: '/og/sponsor/image.webp'
      path: '/og/sponsor/image.webp'
      fullPath: '/og/sponsor/image.webp'
      preLoaderRoute: typeof OgSponsorImageDotwebpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MotivationRoute: MotivationRoute,
  SponsorRoute: SponsorRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  OgDocsSplatRoute: OgDocsSplatRoute,
  OgHomeImageDotwebpRoute: OgHomeImageDotwebpRoute,
  OgMotivationImageDotwebpRoute: OgMotivationImageDotwebpRoute,
  OgSponsorImageDotwebpRoute: OgSponsorImageDotwebpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
