// Generated by @taserjs/cli. Do not edit directly.
import { createTaserApp } from "@taserjs/runtime";
import taser from "../taser.js";
import layout_0 from "../routes/$.js";
import route_0 from "../routes/index.get.js";
import route_1 from "../routes/ping.get.js";
import route_2 from "../routes/users.get.js";

export type LayoutTree = {
  "/*": typeof layout_0;
};

export const layoutManifest = {
    "/*": layout_0,
} as const;

export const routeManifest = {
  layouts: layoutManifest,
  routes: {
    "/": {
      GET: {
        layouts: ["/*"],
        route: route_0,
      },
    },
    "/ping": {
      GET: {
        layouts: ["/*"],
        route: route_1,
      },
    },
    "/users": {
      GET: {
        layouts: ["/*"],
        route: route_2,
      },
    },
  },
} as const;

export type RouteManifest = typeof routeManifest;
export type AppManifest = RouteManifest;

export const app = createTaserApp(routeManifest, taser);
export default app;
export const createApp = (overrideTaser?: typeof taser) =>
  createTaserApp(routeManifest, overrideTaser ?? taser);

export type RoutePath = "/" | "/ping" | "/users";

export type LayoutHierarchy = {
  "/*": readonly [];
};

export type RouteByPathMethod = {
    "/": {
      GET: {
        layouts: readonly ["/*"];
      };
    };
    "/ping": {
      GET: {
        layouts: readonly ["/*"];
      };
    };
    "/users": {
      GET: {
        layouts: readonly ["/*"];
      };
    };
};

export type AppContext = typeof taser.$Infer.Context;

declare module "@taserjs/router" {
  interface RouterRegister {
    RoutePath: RoutePath;
    LayoutTree: LayoutTree;
    LayoutHierarchy: LayoutHierarchy;
    RouteByPathMethod: RouteByPathMethod;
    AppContext: AppContext;
  }
}
