// Generated by @taserjs/cli. Do not edit directly.
import { createTaserApp } from "@taserjs/runtime";
import taser from "../taser.js";
import layout_0 from "../routes/profile.js";
import route_0 from "../routes/hello.get.js";
import route_1 from "../routes/index.get.js";
import route_2 from "../routes/profile.get.js";

export type LayoutTree = {
  "/profile/*": typeof layout_0;
};

export const layoutManifest = {
    "/profile/*": layout_0,
} as const;

export const routeManifest = {
  layouts: layoutManifest,
  routes: {
    "/hello": {
      GET: {
        layouts: [],
        route: route_0,
      },
    },
    "/": {
      GET: {
        layouts: [],
        route: route_1,
      },
    },
    "/profile": {
      GET: {
        layouts: ["/profile/*"],
        route: route_2,
      },
    },
  },
} as const;

export type RouteManifest = typeof routeManifest;
export type AppManifest = RouteManifest;

export const app = createTaserApp(routeManifest, taser);
export default app;
export const createApp = (overrideTaser?: typeof taser) =>
  createTaserApp(routeManifest, overrideTaser ?? taser);

export type RoutePath = "/hello" | "/" | "/profile";

export type LayoutHierarchy = {
  "/profile/*": readonly [];
};

export type RouteByPathMethod = {
    "/hello": {
      GET: {
        layouts: readonly [];
      };
    };
    "/": {
      GET: {
        layouts: readonly [];
      };
    };
    "/profile": {
      GET: {
        layouts: readonly ["/profile/*"];
      };
    };
};

export type AppContext = typeof taser.$Infer.Context;

declare module "@taserjs/router" {
  interface RouterRegister {
    RoutePath: RoutePath;
    LayoutTree: LayoutTree;
    LayoutHierarchy: LayoutHierarchy;
    RouteByPathMethod: RouteByPathMethod;
    AppContext: AppContext;
  }
}
