export const HTTP_VERBS = ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD"] as const;

export const ROUTE_VERB_PATTERN = /\.(get|post|put|delete|patch|options|head|any|all)\.ts$/i;

export const DEFAULT_MANIFEST_HEADER = [
  "/* eslint-disable */",
  "/* prettier-ignore */",
  "// @ts-nocheck",
  "// Generated by TaserJS - DO NOT EDIT",
] as const;

export const DEFAULT_SERVER_DIR = "src";
export const DEFAULT_ROUTES_DIR = "routes";
export const DEFAULT_ENTRY = "#taserjs/router";
export const DEFAULT_SERVER_ENTRY = "server.ts";
export const DEFAULT_IGNORE = ["**/-*"] as const;
export const DEFAULT_GENERATED_TYPES_DIR = ".taser/types";
