import { HTTP_METHODS } from "@taserjs/router-utils/http";

export { HTTP_VERBS, HTTP_METHODS } from "@taserjs/router-utils/http";

const ROUTE_VERB_NAMES = [...HTTP_METHODS.map((method) => method.toLowerCase()), "any", "all"];

export const ROUTE_VERB_PATTERN = new RegExp(`\\.(${ROUTE_VERB_NAMES.join("|")})\\.ts$`, "i");

export const DEFAULT_MANIFEST_HEADER = [
  "/* eslint-disable */",
  "/* prettier-ignore */",
  "// @ts-nocheck",
  "// Generated by TaserJS - DO NOT EDIT",
] as const;

export const ROUTES_ALIAS_ID = "#taserjs/routes";
export const SERVER_ENTRY_ALIAS_ID = "#taserjs/server-entry";

export const VIRTUAL_MANIFEST_ID = "#taserjs/virtual/manifest";
export const RESOLVED_VIRTUAL_MANIFEST_ID = "\0#taserjs/virtual/manifest";

export const VIRTUAL_ENTRY_ID = "#taserjs/virtual/entry";
export const RESOLVED_VIRTUAL_ENTRY_ID = "\0#taserjs/virtual/entry";

export const VIRTUAL_APP_ID = "#taserjs/virtual/app";
export const RESOLVED_VIRTUAL_APP_ID = "\0#taserjs/virtual/app";

export const DEFAULT_SERVER_DIR = "src";
export const DEFAULT_ROUTES_DIR = "routes";
export const DEFAULT_ENTRY = "taser.ts";
export const DEFAULT_SERVER_ENTRY = "server.ts";
export const DEFAULT_IGNORE = ["**/-*"] as const;
export const DEFAULT_GENERATED_TYPES_DIR = ".taser/types";
export const DEFAULT_ROUTES_TYPES_FILENAME = "routes.d.ts";
export const DEFAULT_VIRTUAL_TYPES_FILENAME = "virtual.d.ts";
