import {
  DEFAULT_CONFIG_SCHEMA,
  DEFAULT_ENTRY,
  DEFAULT_OUTPUT,
  DEFAULT_ROUTES,
} from "../constants.js";
import type { GeneratorConfigFile } from "./schema.js";

export function defaultConfigValues(): GeneratorConfigFile {
  return {
    routes: DEFAULT_ROUTES,
    output: DEFAULT_OUTPUT,
    entry: DEFAULT_ENTRY,
    extension: true,
    ignorePrefix: "-",
    ignorePattern: undefined,
    quiet: false,
    quotes: "single",
    semi: false,
    header: [
      "/* eslint-disable */",
      "// Auto-generated by @taserjs/router-generator — do not edit.",
      "",
    ],
    footer: [],
    format: true,
    validate: true,
  };
}

export function formatDefaultConfigFile(schemaPath: string = DEFAULT_CONFIG_SCHEMA): string {
  const config = {
    $schema: schemaPath,
    routes: DEFAULT_ROUTES,
    output: DEFAULT_OUTPUT,
    entry: DEFAULT_ENTRY,
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}
