import { existsSync, promises as fsp } from "node:fs";
import { join, relative, resolve } from "pathe";
import { createHash } from "node:crypto";
import type { GeneratedModel } from "@taserjs/router-generator";
import { emitTypeDeclarationsSource } from "@taserjs/router-generator";

function hashContent(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

let lastWrittenHash: string | undefined;

export async function writeTaserTypes(
  model: GeneratedModel,
  options: {
    rootDir: string;
    quotes?: "single" | "double" | undefined;
    header?: string[] | undefined;
  },
): Promise<boolean> {
  const rootDir = resolve(options.rootDir || ".");
  const typesDir = resolve(rootDir, ".taser/types");
  const targetFile = join(typesDir, "routes.d.ts");

  const header =
    options.header && options.header.length > 0
      ? options.header
      : [
          "/* eslint-disable */",
          "/* prettier-ignore */",
          "// @ts-nocheck",
          "// Generated by @taserjs/vite-plugin - DO NOT EDIT DIRECTLY",
        ];

  const code = emitTypeDeclarationsSource(model, {
    header,
    footer: [],
    quotes: options.quotes ?? "double",
  });

  const contentHash = hashContent(code);
  if (contentHash === lastWrittenHash && existsSync(targetFile)) {
    return false;
  }

  await fsp.mkdir(typesDir, { recursive: true });
  await fsp.writeFile(targetFile, code, "utf8");
  lastWrittenHash = contentHash;

  await ensureTsConfigIncludes(rootDir, targetFile);
  return true;
}

async function ensureTsConfigIncludes(rootDir: string, typesFilePath: string): Promise<void> {
  const tsConfigPath = join(rootDir, "tsconfig.json");
  if (!existsSync(tsConfigPath)) {
    return;
  }

  try {
    const raw = await fsp.readFile(tsConfigPath, "utf8");
    const json = JSON.parse(raw);
    json.include = json.include || [];

    const relPath = relative(rootDir, typesFilePath);
    const pattern = relPath.startsWith(".") ? relPath : `./${relPath}`;
    const globPattern = relPath.replace(/routes\.d\.ts$/, "**/*");
    const globInclude = globPattern.startsWith(".") ? globPattern : `./${globPattern}`;

    const hasExact = json.include.includes(pattern);
    const hasGlob = json.include.includes(globInclude);

    if (!hasExact && !hasGlob) {
      json.include.push(pattern);
      await fsp.writeFile(tsConfigPath, JSON.stringify(json, null, 2) + "\n", "utf8");
    }
  } catch {
    // ignore parse errors
  }
}
