import { existsSync, promises as fsp } from "node:fs";
import { join, relative, resolve } from "pathe";
import { createHash } from "node:crypto";
import { parse, type ParseError } from "jsonc-parser";
import type { GeneratedModel } from "@taserjs/router-generator";
import { emitTypeDeclarationsSource } from "@taserjs/router-generator";
import { ROUTES_ALIAS_ID } from "./aliases.js";

function hashContent(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

/**
 * Caller-owned memo that lets repeated writes from the same context skip
 * redundant disk I/O. Deliberately not module-level: independent consumers
 * (dev server, CLI `taser generate`) must never suppress each other's writes.
 */
export type TypeWriterState = { lastHash?: string };

export async function writeTaserTypes(
  model: GeneratedModel,
  options: {
    rootDir: string;
    quotes?: "single" | "double" | undefined;
    header?: string[] | undefined;
    /** Absolute routes dir; when set, emitted d.ts import specifiers are portable relative paths. */
    routesDir?: string | undefined;
    state?: TypeWriterState | undefined;
  },
): Promise<boolean> {
  const rootDir = resolve(options.rootDir || ".");
  const typesDir = resolve(rootDir, ".taser/types");
  const targetFile = join(typesDir, "routes.d.ts");

  const header =
    options.header && options.header.length > 0
      ? options.header
      : [
          "/* eslint-disable */",
          "/* prettier-ignore */",
          "// @ts-nocheck",
          "// Generated by @taserjs/vite-plugin - DO NOT EDIT DIRECTLY",
        ];

  // d.ts files are consumed by tsc, not a bundler — virtual aliases would never
  // resolve. Rebase specifiers onto typesDir-relative paths instead.
  let rewriteImportPath: ((spec: string) => string) | undefined;
  if (options.routesDir) {
    const routesDir = resolve(options.routesDir);
    const aliasPrefix = `${ROUTES_ALIAS_ID}/`;
    rewriteImportPath = (spec) => {
      const targetAbs = spec.startsWith(aliasPrefix)
        ? join(routesDir, spec.slice(aliasPrefix.length))
        : resolve(spec);
      const rel = relative(typesDir, targetAbs);
      // `.taser/…`-style relatives already start with a dot but still need `./`
      // to be valid module specifiers.
      return rel.startsWith("./") || rel.startsWith("../") ? rel : `./${rel}`;
    };
  }

  const code = emitTypeDeclarationsSource(model, {
    header,
    footer: [],
    quotes: options.quotes ?? "double",
    rewriteImportPath,
  });

  const contentHash = hashContent(code);
  if (options.state && contentHash === options.state.lastHash && existsSync(targetFile)) {
    return false;
  }

  await fsp.mkdir(typesDir, { recursive: true });
  await fsp.writeFile(targetFile, code, "utf8");
  if (options.state) {
    options.state.lastHash = contentHash;
  }

  await ensureTsConfigIncludes(rootDir, targetFile);
  return true;
}

async function ensureTsConfigIncludes(rootDir: string, typesFilePath: string): Promise<void> {
  const tsConfigPath = join(rootDir, "tsconfig.json");
  if (!existsSync(tsConfigPath)) {
    return;
  }

  let raw: string;
  try {
    raw = await fsp.readFile(tsConfigPath, "utf8");
  } catch {
    console.warn(`[taser] Could not read ${tsConfigPath}; skipping tsconfig include management.`);
    return;
  }

  // JSONC-tolerant parse: tsconfigs routinely carry comments and trailing commas.
  const errors: ParseError[] = [];
  const json = parse(raw, errors, { allowTrailingComma: true }) as
    | { include?: unknown; [key: string]: unknown }
    | undefined;
  if (errors.length > 0 || typeof json !== "object" || json === null) {
    console.warn(
      `[taser] Could not parse ${tsConfigPath}; `.trim() +
        "skipping include management — add .taser/types to your include array manually.",
    );
    return;
  }

  const relPath = relative(rootDir, typesFilePath);
  const globPattern = relPath.replace(/routes\.d\.ts$/, "**/*");
  // `.taser/…` starts with a dot but still needs an explicit `./` prefix to be
  // a valid include pattern.
  const ensureDotSlash = (value: string) =>
    value.startsWith("./") || value.startsWith("../") ? value : `./${value}`;
  const pattern = ensureDotSlash(relPath);
  const globInclude = ensureDotSlash(globPattern);

  const include = Array.isArray(json.include) ? (json.include as unknown[]) : undefined;
  if (include && (include.includes(pattern) || include.includes(globInclude))) {
    return;
  }

  if (!containsComments(raw)) {
    const nextInclude = [...(include ?? []), pattern];
    await fsp.writeFile(
      tsConfigPath,
      JSON.stringify({ ...json, include: nextInclude }, null, 2) + "\n",
      "utf8",
    );
    return;
  }

  // Commented tsconfig: splice the entry in textually so user comments survive.
  const updated = insertIncludeEntry(raw, JSON.stringify(pattern));
  if (updated !== raw) {
    await fsp.writeFile(tsConfigPath, updated, "utf8");
  }
}

/** Detects `//` and block comments outside of string literals. */
function containsComments(text: string): boolean {
  let inString = false;
  let escaped = false;
  for (let index = 0; index < text.length; index++) {
    const char = text[index];
    if (inString) {
      if (escaped) {
        escaped = false;
      } else if (char === "\\") {
        escaped = true;
      } else if (char === '"') {
        inString = false;
      }
      continue;
    }
    if (char === '"') {
      inString = true;
    } else if (char === "/" && text[index + 1] === "/") {
      return true;
    } else if (char === "/" && text[index + 1] === "*") {
      return true;
    }
  }
  return false;
}

/**
 * Inserts an entry into the tsconfig's `include` array without touching any
 * other byte of the file. Creates the array after the top-level `{` when the
 * key is missing; returns the input unchanged when no object literal exists.
 */
function insertIncludeEntry(raw: string, entryJson: string): string {
  const includeMatch = /"include"\s*:\s*\[/m.exec(raw);
  if (includeMatch) {
    const bracketIndex = includeMatch.index + includeMatch[0].length;
    return `${raw.slice(0, bracketIndex)}\n    ${entryJson},${raw.slice(bracketIndex)}`;
  }

  const braceIndex = raw.indexOf("{");
  if (braceIndex === -1) {
    console.warn(`[taser] tsconfig.json has no object literal; could not add include entry.`);
    return raw;
  }
  return `${raw.slice(0, braceIndex + 1)}\n  "include": [${entryJson}],${raw.slice(braceIndex + 1)}`;
}
