// Generated by @taserjs/cli. Do not edit directly.
import { createTaserApp } from "@taserjs/runtime";
import taser from "../taser.js";
import layout_0 from "../routes/$.js";
import layout_1 from "../routes/_auth/items/$id.js";
import layout_2 from "../routes/_auth.js";
import layout_3 from "../routes/admin.js";
import route_0 from "../routes/[.well-known].get.js";
import route_1 from "../routes/_auth/items/$id/index.get.js";
import route_2 from "../routes/_auth/items/index.get.js";
import route_3 from "../routes/_auth/save.post.js";
import route_4 from "../routes/_auth/token.get.js";
import route_5 from "../routes/files.$.get.js";
import route_6 from "../routes/index.get.js";
import route_7 from "../routes/users.get.js";

export type LayoutTree = {
  "/*": typeof layout_0;
  "/_auth/items/:id/*": typeof layout_1;
  "/_auth/*": typeof layout_2;
  "/admin/*": typeof layout_3;
};

export const layoutManifest = {
    "/*": layout_0,
    "/_auth/items/:id/*": layout_1,
    "/_auth/*": layout_2,
    "/admin/*": layout_3,
} as const;

export const routeManifest = {
  layouts: layoutManifest,
  routes: {
    "/.well-known": {
      GET: {
        layouts: ["/*"],
        route: route_0,
      },
    },
    "/items/:id": {
      GET: {
        layouts: ["/*", "/_auth/*", "/_auth/items/:id/*"],
        route: route_1,
      },
    },
    "/items": {
      GET: {
        layouts: ["/*", "/_auth/*"],
        route: route_2,
      },
    },
    "/save": {
      POST: {
        layouts: ["/*", "/_auth/*"],
        route: route_3,
      },
    },
    "/token": {
      GET: {
        layouts: ["/*", "/_auth/*"],
        route: route_4,
      },
    },
    "/files/*": {
      GET: {
        layouts: ["/*"],
        route: route_5,
      },
    },
    "/": {
      GET: {
        layouts: ["/*"],
        route: route_6,
      },
    },
    "/users": {
      GET: {
        layouts: ["/*"],
        route: route_7,
      },
    },
  },
} as const;

export type RouteManifest = typeof routeManifest;
export type AppManifest = RouteManifest;

export const app = createTaserApp(routeManifest, taser);
export default app;
export const createApp = (overrideTaser?: typeof taser) =>
  createTaserApp(routeManifest, overrideTaser ?? taser);

export type RoutePath = "/.well-known" | "/items/:id" | "/items" | "/save" | "/token" | "/files/*" | "/" | "/users";

export type LayoutHierarchy = {
  "/*": readonly [];
  "/_auth/items/:id/*": readonly ["/*", "/_auth/*"];
  "/_auth/*": readonly ["/*"];
  "/admin/*": readonly ["/*"];
};

export type RouteByPathMethod = {
    "/.well-known": {
      GET: {
        layouts: readonly ["/*"];
      };
    };
    "/items/:id": {
      GET: {
        layouts: readonly ["/*", "/_auth/*", "/_auth/items/:id/*"];
      };
    };
    "/items": {
      GET: {
        layouts: readonly ["/*", "/_auth/*"];
      };
    };
    "/save": {
      POST: {
        layouts: readonly ["/*", "/_auth/*"];
      };
    };
    "/token": {
      GET: {
        layouts: readonly ["/*", "/_auth/*"];
      };
    };
    "/files/*": {
      GET: {
        layouts: readonly ["/*"];
      };
    };
    "/": {
      GET: {
        layouts: readonly ["/*"];
      };
    };
    "/users": {
      GET: {
        layouts: readonly ["/*"];
      };
    };
};

export type AppContext = typeof taser.$Infer.Context;

declare module "@taserjs/router" {
  interface RouterRegister {
    RoutePath: RoutePath;
    LayoutTree: LayoutTree;
    LayoutHierarchy: LayoutHierarchy;
    RouteByPathMethod: RouteByPathMethod;
    AppContext: AppContext;
  }
}
